### ISSUE TITLE
创建不了房间

### ISSUE THREAD

**Issue by MS10755** [VaalaCat/movie-sync-server#1]
我在docker上用centos7镜像创建容器。能打开创建房间的页面，点击加入一直是loading转圈圈。
终端一直提示这个

2022/09/01 02:03:21 getUsers: 123:
2022/09/01 02:03:21 closed client namespace disconnect
2022/09/01 02:03:22 connected: 2
2022/09/01 02:03:28 sync: 123:
2022/09/01 02:03:28 closed client namespace disconnect
2022/09/01 02:03:28 connected: 3
2022/09/01 02:03:38 sync: 123:
2022/09/01 02:03:38 closed client namespace disconnect
2022/09/01 02:03:39 connected: 4
2022/09/01 02:03:48 sync: 123:
2022/09/01 02:03:48 closed client namespace disconnect
2022/09/01 02:03:49 connected: 5
2022/09/01 02:03:58 sync: 123:
2022/09/01 02:03:58 closed client namespace disconnect
2022/09/01 02:04:00 connected: 6
2022/09/01 02:04:08 sync: 123:
2022/09/01 02:04:08 closed client namespace disconnect
2022/09/01 02:04:09 connected: 7
2022/09/01 02:04:14 closed client namespace disconnect
2022/09/01 02:04:30 connected: 8
2022/09/01 02:04:33 getUsers: 合理:
2022/09/01 02:04:33 closed client namespace disconnect
2022/09/01 02:04:34 connected: 9

**Comment by VaalaCat** [comment]
可以f12看看浏览器报错吗，猜测是env文件设置的问题

________________________________
发件人: MS10755 ***@***.***>
发送时间: Thursday, September 1, 2022 10:09:18 AM
收件人: VaalaCat/movie-sync-server ***@***.***>
抄送: Subscribed ***@***.***>
主题: [VaalaCat/movie-sync-server] 创建不了房间 (Issue #1)


我在docker上用centos7镜像创建容器。能打开创建房间的页面，点击加入一直是loading转圈圈。
终端一直提示这个

2022/09/01 02:03:21 getUsers: 123:
2022/09/01 02:03:21 closed client namespace disconnect
2022/09/01 02:03:22 connected: 2
2022/09/01 02:03:28 sync: 123:
2022/09/01 02:03:28 closed client namespace disconnect
2022/09/01 02:03:28 connected: 3
2022/09/01 02:03:38 sync: 123:
2022/09/01 02:03:38 closed client namespace disconnect
2022/09/01 02:03:39 connected: 4
2022/09/01 02:03:48 sync: 123:
2022/09/01 02:03:48 closed client namespace disconnect
2022/09/01 02:03:49 connected: 5
2022/09/01 02:03:58 sync: 123:
2022/09/01 02:03:58 closed client namespace disconnect
2022/09/01 02:04:00 connected: 6
2022/09/01 02:04:08 sync: 123:
2022/09/01 02:04:08 closed client namespace disconnect
2022/09/01 02:04:09 connected: 7
2022/09/01 02:04:14 closed client namespace disconnect
2022/09/01 02:04:30 connected: 8
2022/09/01 02:04:33 getUsers: 合理:
2022/09/01 02:04:33 closed client namespace disconnect
2022/09/01 02:04:34 connected: 9

―

**Comment by MS10755** [comment]
浏览器提示这个

![image](https://user-images.githubusercontent.com/42739344/187818174-483a0f04-2a5a-4502-966a-b190876e62ef.png)

![image](https://user-images.githubusercontent.com/42739344/187818312-89153696-cc12-4ee8-a8c3-2a1a02e2a743.png)

**Comment by VaalaCat** [comment]
二进制文件和web文件的版本是下载的release内的吗

**Comment by MS10755** [comment]
后端我是直接克隆的仓库，前端是下载的release里的

**Comment by VaalaCat** [comment]
前后端现在最新的能匹配的版本是两个dev分支内的版本，要么两个都是release下载的，要么必须两个都是dev分支build出来的

**Comment by MS10755** [comment]
> 前后端现在最新的能匹配的版本是两个dev分支内的版本，要么两个都是release下载的，要么必须两个都是dev分支build出来的

可以咯，谢谢大佬~

**Comment by VaalaCat** [comment]
前后端现在最新的能匹配的版本是两个dev分支内的版本，要么两个都是release下载的，要么必须两个都是dev分支build出来的
________________________________
发件人: MS10755 ***@***.***>
发送时间: Thursday, September 1, 2022 10:31:41 AM
收件人: VaalaCat/movie-sync-server ***@***.***>
抄送: Vaala Cat ***@***.***>; Comment ***@***.***>
主题: Re: [VaalaCat/movie-sync-server] 创建不了房间 (Issue #1)


后端我是直接克隆的仓库，前端是下载的release里的

env文件设置
[image]<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F42739344%2F187819100-ef9e7e3d-ad5c-440e-8f50-38546ee62abb.png&data=05%7C01%7C%7C63ddbc25147140cd771608da8bc21ad3%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637975963045521453%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=x78a8LmKhJ9wMBbyhv6w%2FTJ2f2D9iUZDPpMUpw3WiMc%3D&reserved=0>

―
